<?php
define('THIS_IS_SOMEWHAT',__('This is somewhat embarrassing, isn&rsquo;t it?', 'salejunction'));
define('IT_SEEMS_WE',__('It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the links below, can help.', 'salejunction'));
define('MOST_USED_CATEGORIES',__('Most Used Categories', 'salejunction'));
define('MONTHLY_ARCHIVES',__('Try looking in the monthly archives. %1$s', 'salejunction'));
define('SORRY_NO_POST_MATCHED',__('Sorry, no posts matched your criteria.', 'salejunction'));
define('NOTHING_FOUND',__('Nothing Found here', 'salejunction'));
define('NOTHING_MATCHED',__('Sorry, but nothing matched your search criteria. Please try again with some diffrent keyword', 'salejunction'));
define('CATEGORIES',__('Categories', 'salejunction'));
define('ARCHIVES',__('Archives', 'salejunction'));
define('BLOG_ARCHIVES',__('Blog Archives', 'salejunction'));
define('CATEGORY_ARCHIVES',__('Category Archives: %s', 'salejunction'));
define('PAGE',__('Page %s', 'salejunction'));
define('SEARCH_RESULT',__('Search Results for: %s', 'salejunction'));
define('TAG_ARCHIVES',__('Tag Archives: %s', 'salejunction'));
define('DAILY_ARCHIVES',__('Daily Archives: %s', 'salejunction'));
define('MONTHLY_ARCHIVE',__('Monthly Archives: %s', 'salejunction'));
define('YEARLY_ARCHIVES',__('Yearly Archives: %s', 'salejunction'));
define('AUTHOR_ARCHIVES',__('Author Archives: %s', 'salejunction'));
define('ABOUT',__('About: %s', 'salejunction'));
define('HOME_TEXT',__('Home', 'salejunction'));
define('THIS_ENTRY_WAS_POSTED_IN',__('This entry was posted in %1$s', 'salejunction'));
define('PERMALINK',__('permalink', 'salejunction'));
define('BOOKMARK_THE',__('Bookmark the', 'salejunction'));
define('PRIMARY_WIDGET',__('Primary Widget Area', 'salejunction'));
define('THE_PRIMARY_WIDGET',__('The primary widget area', 'salejunction'));
define('SECONDRY_WIDGET',__('Secondary Widget Area', 'salejunction'));
define('THE_SECONDRY_WIDGET',__('The secondary widget area', 'salejunction'));
define('HOME_PAGE_SIDEBAR_WIDGET_AREA',__('Home Page Sidebar Feature widget area', 'salejunction'));
define('THE_HOME_PAGE_SIDEBAR_WIDGET_AREA',__('The Home Page Sidebar Feature widget area', 'salejunction'));
define('FIRST_FOOTER_WIDGET',__('First Footer Widget Area', 'salejunction'));
define('THE_FIRST_FOOTER_WIDGET',__('The first footer widget area', 'salejunction'));
define('SECONDRY_FOOTER_WIDGET',__('Second Footer Widget Area', 'salejunction'));
define('THE_SECONDRY_FOOTER_WIDGET',__('The second footer widget area', 'salejunction'));
define('THIRD_FOOTER_WIDGET',__('Third Footer Widget Area', 'salejunction'));
define('THE_THIRD_FOOTER_WIDGET',__('The third footer widget area', 'salejunction'));
define('FOURTH_FOOTER_WIDGET',__('Fourth Footer Widget Area', 'salejunction'));
define('THE_FOURTH_FOOTER_WIDGET',__('The fourth footer widget area', 'salejunction'));
define('OLDER_POSTS',__('&larr; Older posts', 'salejunction'));
define('NEWER_POSTS',__('Newer posts &rarr;', 'salejunction'));
define('PREV_POST',__(' Previous Post', 'salejunction'));
define('NEXT_POST',__('Next Post ', 'salejunction'));
define('READ_MORE',__('Read More', 'salejunction'));
define('SND_MSG',__('Send Your Message', 'salejunction'));
define('RETURN_TO',__('Return to %s', 'salejunction'));
define('BY_AUTHOR',__('By %2$s', 'salejunction'));
define('VIEW_ALL_POST_BY',__('View all posts by %s', 'salejunction'));
define('PUBLISHED_BY',__('Published %2$s', 'salejunction'));
define('FULL_SIZE_IS_PIXEL',__('Full size is %s pixels', 'salejunction'));
define('LINK_TO_FULL_SIZE_IMAGE',__('Link to full-size image', 'salejunction'));
define('EDIT_TEXT',__('Edit', 'salejunction'));
define('CONTINUE_READING',__('Continue reading &rarr;', 'salejunction'));
define('PAGES_COLON',__('Pages:', 'salejunction'));
define('CONTINUE_READING_DOTS',__('Read More...', 'salejunction'));
define('POSTED_BY',__('Posted by', 'salejunction'));
define('AND_TAGGED',__('and tagged', 'salejunction'));
define('PDT_SOLD',__('Total Product Sold:', 'salejunction'));
define('RLS_DATE',__('Release Date:', 'salejunction'));
define('TTL_CMMNT',__('Total Comments:', 'salejunction'));
define('ITEM_CAT',__('Item Category:', 'salejunction'));
define('MORE_IN',__('More In', 'salejunction'));
define('RCNT_ADDED',__('Recently Added', 'salejunction'));
define('PRDT_DTL',__('Product Details', 'salejunction'));
define('MOST_RCNT',__('Most Recent', 'salejunction'));
define('MOST_PPLR',__('Most Popular', 'salejunction'));
define('MOST_SOLD',__('Most Sold', 'salejunction'));
define('THANX_EMAIL',__('Thanks, your email was sent successfully.', 'salejunction'));
define('MAIN_MENU',__('Main Menu', 'salejunction'));
?>